# Generated by Django 5.0.1 on 2024-04-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0003_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact'},
        ),
    ]
